# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HM5IBpVwXskP28TW34LDae68vwG4YnTR
"""

print('the frist thing')

